config/routes.rb
KillerGame::Application.routes.draw do
  devise_for :users

  resources :players, :except => [:index] do
    get 'player_interface', :on => :member
  end

  resources :missions, :except => [:index]
  resources :games, :only => [:create, :show, :destroy] do
    get 'init_game', :on => :collection
  end

  resources :game_items, :only => [:show]

  match 'game_items/:id/killed' => 'game_items#killed', :as => 'player_killed'

  root :to => 'games#index'
  match 'clean_games' => 'game#clean_games'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :finished, :winner, :winner_id

  has_many :game_items, :class_name => 'GameItem'

  belongs_to :winner, :class_name => 'GameItem'

  def launch_game(players_names, missions)
    game_items = []
    players_names.each do |player|
      game_items << GameItem.new(:player => player, :game => self, :mission => missions.pop, :killed => false)
    end

    game_items.each_with_index do |game_item, index|
      game_item.next_game_item = if index < game_items.count - 1
                                   game_items[index + 1]
                                 else
                                   game_items.first
                                 end
      game_item.save
    end
  end

  def sorted_game_items
    sorted_items = []
    temp = self.game_items.dup.select{|game_item| !game_item.killed?}
    sorted_items << temp.pop
    until temp.empty?
      next_game_item  = temp.select{|gi| gi == sorted_items.last.next_game_item}.try(:first)
      sorted_items << temp.delete(next_game_item)
    end
    sorted_items
  end

  def update_game
    if self.game_items.select{|game_item| !game_item.killed?}.count <= 1
      self.finished = true
      self.winner = self.game_items.select{|game_item| !game_item.killed?}.first
      self.save
    end
  end
end

app/models/game_item.rb
class GameItem < ActiveRecord::Base
  attr_accessible :player, :next_game_item, :mission, :game, :next_game_item_id, :mission_id, :game_id, :killed

  #belongs_to :player,   :class_name => 'Player'
  belongs_to :mission,  :class_name => 'Mission'
  belongs_to :game,     :class_name => 'Game'

  belongs_to :next_game_item,   :class_name => 'GameItem'

end

app/models/mission.rb
class Mission < ActiveRecord::Base
  attr_accessible :description

  has_one :victim, :class_name => 'Player', :inverse_of => :weak_point, :foreign_key => :weak_point_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :pseudo
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery
end

app/controllers/game_items_controller.rb
class GameItemsController < ApplicationController

  def killed
    game_item = GameItem.find(params[:id])

    prev_game_item = GameItem.where(:game_id => game_item.game.id, :next_game_item_id => game_item.id, :killed => false).try(:first)

    unless prev_game_item.nil?
      prev_game_item.next_game_item = game_item.next_game_item
      game_item.killed = true
      prev_game_item.save
      game_item.save
    end

    game_item.game.update_game

    respond_to do |format|
      format.html{redirect_to game_path(game_item.game)}
    end
  end

  def show
    @game_item = GameItem.find(params[:id])
    respond_to do |format|
      format.html
    end
  end
end

app/controllers/games_controller.rb
# -*- encoding : utf-8 -*-
class GamesController < ApplicationController
  def index
    @missions = Mission.all
    @message = params.has_key?(:message) ? params[:message] : nil
    @games = Game.all
  end

  def create
    @players = []
    players_name = params[:players].select{|n| !n.blank?}

    @missions = Mission.all

    if players_name.count < 2
      respond_to do |format|
        format.html{ redirect_to root_path(:message => "Il faut un peu plus de joueurs pour pouvoir lancer le jeu...")}
      end
    elsif @missions.count < @players.count
      respond_to do |format|
        format.html{ redirect_to root_path(:message => "Il n'y a pas assez de missions, il en manque #{@players.count - @missions.count} pour pouvoir lancer le jeu...")}
      end
    else
      @game = Game.create(:finished => false)
      @game.launch_game(players_name, @missions.shuffle)

      respond_to do |format|
        format.html{redirect_to game_path(@game)}
      end
    end
  end

  def destroy
    game = Game.find(params[:id])
    game.delete

    respond_to do |format|
      format.html{redirect_to root_path}
    end

  end

  def show
    @game = Game.find(params[:id])
  end

  def clean_games
    games = Game.all
    games.each do |game|
      wrong_game_items = game.game_items.select{|gi| gi.player.nil? || gi.next_game_item.nil? || gi.mission.nil?}
      game.delete unless wrong_game_items.empty?
    end

    respond_to do |format|
      format.html{redirect_to root_path}
    end
  end

  def init_game

  end

end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController

  def new
    @mission = Mission.new
  end

  def create
    Mission.create(params[:mission])
    respond_to do |format|
      format.html{redirect_to root_path}
    end
  end

  def edit
    @mission = Mission.find(params[:id])
  end

  def update
    Mission.update_attributes(params[:mission])
    respond_to do |format|
      format.html{redirect_to root_path}
    end
  end

  def destroy
    mission = Mission.find(params[:id])
    mission.delete

    respond_to do |format|
      format.html{redirect_to root_path}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/game_items/show.html.erb
<%
   player_pseudo = @game_item.player
   victim_pseudo = @game_item.next_game_item.player
   mission = @game_item.next_game_item.mission.description
%>

<h1>Fiche de Jeu</h1>
<p class="player_pseudo"><%= player_pseudo %></p>

<% if @game_item.killed? %>
    TU ES MORT... MOUAHAHAHAAAA !!!
<% else %>
    <div>
      <h2>Victime</h2>
      <h2><%= victim_pseudo %></h2>
      <h2>Mission</h2>
      <p><%= mission %></p>
    </div>

    <%= link_to 'J\'ai été tué...', player_killed_path(@game_item) %>
    <br />
<% end %>

<%= link_to 'Retour au jeu',  game_path(@game_item.game) %>
<br />
<%= link_to 'Retour à l\'accueil',  root_path %>

app/views/games/_game.html.erb
<%= stylesheet_link_tag "game" %>

<% if @game.finished? %>
<div>
  Le jeu est terminé, et le grand gagnant est : <%= @game.winner.try(:player) %>
</div>
<% else %>
    <ul>
      <% @game.game_items.sort_by{|gi| gi.player}.each do |game_item| %>
          <li class="<%= game_item.killed? ? "dead" : "alive" %>"><%= link_to game_item.player, game_item_path(game_item) %></li>
      <% end %>
    </ul>

    <table>
      <thead>
      <th>Joueur</th>
      <th>Victime</th>
      <th>Mission</th>
      </thead>
      <tbody>
      <% @game.sorted_game_items.each do |game_item| %>
          <tr>
            <td><%= game_item.player %></td>
            <td><%= game_item.next_game_item.player %></td>
            <td><%= game_item.next_game_item.mission.try(:description) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% end %>
<%= link_to 'Retour Accueil',  root_path %>

app/views/games/index.html.erb
<h1>Le jeu du Killer</h1>

<div>
  <h3>Les jeux en cours :</h3>

  <table>
    <thead>
    <th>Jeux</th>
    <th>Gagnant</th>
    <th>Actions</th>
    </thead>
    <tbody>
    <% @games.each do |game| %>
        <tr>
          <% if game.finished? %>
              <td>Jeu n°<%= game.id %> terminé</td>
              <td><%= game.winner.try(:player) %></td>
              <td><%= link_to 'Supprimer ce jeu', game_path(game), :method => :delete %> </td>
          <% else %>
              <td><%= link_to "Jeu n°#{game.id}", game_path(game) %></td>
              <td></td>
              <td><%= link_to 'Supprimer ce jeu', game_path(game), :method => :delete %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>

  <div>
    <%= link_to 'Lancer un nouveau jeu !', init_game_games_path, :class => 'button' %>
    <% if @message %>
        <p>
          <%= @message %>
        </p>
    <% end %>
  </div>
</div>
<div>
  <h3>Les missions disponibles :</h3>

  <table>
    <thead>
    <th>Description</th>
    <th>Actions</th>
    </thead>
    <tbody>
    <% @missions.each do |mission| %>
        <tr>
          <td><%= mission.description %></td>
          <td><%= link_to 'Modifier', edit_mission_path(mission) %> - <%= link_to 'Supprimer', mission_path(mission), :method => :delete %></td>
        </tr>
    <% end %>
    </table>
  <%= link_to 'Ajouter une mission', new_mission_path, :class => 'button' %>
</div>

app/views/games/init_game.html.erb
<h1>Nouveau Jeu</h1>

<h2>Liste des joueurs</h2>

<%= form_tag games_path do %>
    <%= link_to 'Ajouer un joueur', '#', :onclick => 'addPlayer(this);' %>
    <div class="players">
        <%= text_field_tag 'players[]' %>
    </div>
    <%= submit_tag 'Lancer le jeu' %>
<% end %>

app/views/games/show.html.erb
<%= render :partial => 'games/game', locals: {game: @game} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Killer Game</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<p class="logout"><%= link_to 'Déconnexion', destroy_user_session_path, :method => :delete if current_user %></p>
<div id="container">
<%= yield %>
</div>

</body>
</html>

app/views/missions/_form.html.erb
<h1>Nouvelle mission</h1>

<%= form_for mission do |f| %>
    <div>
    <%= label_tag 'Description : ' %>
    </div>
    <%= f.text_area :description %>
    <div>
      <%= f.submit 'Ajouter mission', :class => 'button' %>
    </div>
<% end %>
<br />
<%= link_to 'Retour à l\'accueil',  root_path %>

app/views/missions/edit.html.erb
<%= render :partial => 'missions/form', :locals => {:mission => @mission} %>

app/views/missions/new.html.erb
<%= render :partial => 'missions/form', :locals => {:mission => @mission} %>